### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by fmwl2233** [Fatfish588/jmid2name-hoshino#2]
正常查询114514都查不到。返回为匹配到搜索结果。

**Comment by Fatfish588** [comment]
> 正常查询114514都查不到。返回为匹配到搜索结果。

可以提供一下截图和日志吗

**Comment by fmwl2233** [comment]
> > 正常查询114514都查不到。 返回为匹配到搜索结果。
> 
> 可以提供一下截图和日志吗

[2024-05-22 23:56:40,221 nonebot] INFO: Self: 3497663779, Message 1329225738 from 2454872712@[群:673979166]: 'jm114514'
[2024-05-22 23:56:40,224 禁漫ID转换为本子名] INFO: Message 1329225738 triggered I_dont_know_how_to_type_japanese.
[2024-05-22 23:56:42,323 禁漫ID转换为本子名] ERROR: <class 'jmcomic.jm_exception.RegularNotMatchException'> occured when I_dont_know_how_to_type_japanese handling message 1329225738.
[2024-05-22 23:56:42,324 禁漫ID转换为本子名] ERROR: 未匹配到搜索结果
Traceback (most recent call last):
  File "D:\hoshinobot\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "D:\hoshinobot\HoshinoBot\hoshino\modules\jmid2name-hoshino\jmid2name.py", line 51, in I_dont_know_how_to_type_japanese
    page = client.search_site(search_query=str(target_numbers))
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_client_interface.py", line 326, in search_site
    return self.search(search_query, page, 0, order_by, time)
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_client_impl.py", line 180, in cache_wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_client_impl.py", line 327, in search
    return JmPageTool.parse_html_to_search_page(resp.text)
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_toolkit.py", line 408, in parse_html_to_search_page
    html = PatternTool.require_match(
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_toolkit.py", line 337, in require_match
    ExceptionTool.raises_regex(
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_exception.py", line 108, in raises_regex
    cls.raises(
  File "C:\Program Files\Python38\lib\site-packages\jmcomic\jm_exception.py", line 100, in raises
    raise e
jmcomic.jm_exception.RegularNotMatchException: 未匹配到搜索结果

但独运行禁漫网站检查插件可以确定连接正常

**Comment by Fatfish588** [comment]
> 正常查询114514都查不到。返回为匹配到搜索结果。

原因已找到，是因为在config中配置的domain们可能已经过期失效了，jm换域名是挺勤快的。解决方案是更新依赖并在conifg中去掉domain，如下：
1、若已经安装本插件，运行以下命令更新依赖并安装新版本所需要的其他依赖
```bash
pip install jmcomic -i https://pypi.org/project -U
```
```bash
pip install commonX -U
```
2、在config中将domain的值删除换成空列表[ ]
![image](https://github.com/Fatfish588/jmid2name-hoshino/assets/59791439/1d9481a1-4773-453b-9533-e672e76c9a70)
稍后会更新仓库，感谢您的支持
